[build]
  publish = "."

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/specials"
  to = "/specials.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301
